# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Manual Deployment

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Commit ID'
        required: true
        default: 'main'

env:
  AZURE_WEBAPP_NAME: team3FnApp003
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  NODE_VERSION: '14'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.ref }}
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test --if-present

    - name: 'Deploy to Azure WebApp'
      uses: Azure/functions-action@v1.4.4
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        slot-name: ''
